#!/bin/bash

#Look to see what's in the file


#Locate the files in the fastq folder 
/localdisk/data/BPSM/AY21/fastq

#Count the total number of files in the folder
ls | grep "100k" | wc -l

#Count the number of Clone1 files
ls | grep "100k.C1" | wc -l

#Count the number of Clone2 files 
ls | grep "100k.C2" | wc -l

#Count the number of WT files:
ls | grep "100k.WT" | wc -l

#Look at the sample details in 100k.fqfiles
head 100k.fqfiles            

#The headings of the table can be viewed - appears to be 7 tabs

#Check the bottom of the file:
tail 100k.fqfiles

#Check to see how many lines are present with 7 tabs:
cat 100k.fqfiles | awk '{
FS="\t" ;
if(NF == 7)
{print $0 ;}
}' | wc -l

#Check if there's any lines without 7 tabs:
cat 100k.fqfiles | awk '{
FS="\t" ;
if(NF !== 7)
{print $0 ;}
}' | wc -l

#No. of rows excluding header
grep -v "ID" 100k.fqfiles | awk '{
FS="\t" ;
if(NF == 7)
{print $0 ;}
}' | wc -l



